services:
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9002:9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped
    networks:
      - network
volumes:
  database_data:
  minio_data:

  database_test_data:

networks:
  network:
    driver: bridge
