name: Pull Request Tests # Nombre del workflow

on:
  pull_request: # Se ejecuta en cada pull request
    branches:
      - main # Se ejecuta solo para la rama main

jobs:
  
  tests: # Job para ejecutar pruebas
    runs-on: ubuntu-latest # Crea un entorno virtual en Ubuntu
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: db_test
          POSTGRES_USER: user_test
          POSTGRES_PASSWORD: password_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U user_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    strategy:
      matrix:
        project: [backend]
    steps:
      - name: Checkout código # Clona el repositorio en el entorno virtual
        uses: actions/checkout@v4 # Usa una acción de GitHub

      - name: Instalar Node.js # Instala Node.js en el entorno virtual
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Instalar dependencias y ejecutar pruebas (${{ matrix.project }})
        run: |
          cd ${{ matrix.project }}
          npm ci
          if [ "${{ matrix.project }}" = "frontend" ]; then
            npm run build --if-present
          fi
          npm run test